include:
  - ./docker-compose.observability.yml

services:
  postgresql:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .vali.env

  dbmate:
    image: amacneil/dbmate
    volumes:
      - ./validator/db:/db
    command: --wait up
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .vali.env
    networks:
      - postgres_network
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?sslmode=disable

  redis:
    image: redis/redis-stack:latest
    ports:
      - "127.0.0.1:6379:6379"
    deploy:
      restart_policy:
        condition: on-failure

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_network

volumes:
  postgres_data:
  minio_data:

networks:
  postgres_network:
  redis_network:
  minio_network: