# Deploy this on your observability/monitoring server
version: '3.8'

services:
  # Nginx reverse proxy for SSL termination and authentication
  nginx-proxy:
    container_name: god-nginx-proxy
    image: nginx:alpine
    restart: always
    ports:
      - "443:443"
      - "3001:3001"  # Grafana HTTPS
      - "3101:3101"  # Loki HTTPS
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
      - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - grafana-training
      - loki-training
    networks:
      - training-observability

  grafana-training:
    container_name: god-grafana-training
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_TRAINING_USERNAME:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_TRAINING_PASSWORD:-changeme}
      GF_INSTALL_PLUGINS: redis-datasource
      GF_SERVER_HTTP_PORT: 3000
      GF_SERVER_ROOT_URL: https://${OBSERVABILITY_DOMAIN:-localhost}:3001
      # Security settings
      GF_AUTH_ANONYMOUS_ENABLED: ${GRAFANA_ANONYMOUS_ENABLED:-false}
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_SECURITY_ALLOW_EMBEDDING: "false"
      GF_SECURITY_COOKIE_SAMESITE: "lax"
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_SECURITY_STRICT_TRANSPORT_SECURITY: "true"
      GF_SECURITY_X_CONTENT_TYPE_OPTIONS: "true"
      GF_SECURITY_X_XSS_PROTECTION: "true"
    volumes:
      - ./config/grafana-training-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./config/grafana-training-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./config/grafana-training-dashboard.json:/var/lib/grafana/dashboards/grafana-training-dashboard.json:ro
      - grafana-training-data:/var/lib/grafana
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 512M
    networks:
      - training-observability
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  loki-training:
    container_name: god-loki-training
    image: grafana/loki:main
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      LOKI_AUTH_ENABLED: ${LOKI_AUTH_ENABLED:-true}
    volumes:
      - loki-training:/loki
      - ./config/loki-training-config.yaml:/etc/loki/local-config.yaml:ro
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 1G
    networks:
      - training-observability
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus-training:
    container_name: god-prometheus-training
    image: prom/prometheus:latest
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - prometheus-training:/prometheus
      - ./config/prometheus-training-config.yaml:/etc/prometheus/prometheus.yml:ro
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 512M
    networks:
      - training-observability
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  training-observability:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  grafana-training-data:
  loki-training:
  prometheus-training: