{
 "title": "Validator API Metrics",
 "tags": [
  "validator",
  "api"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"otel-collector-services\"}[5m])) by (le, path, method))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"otel-collector-services\"}[5m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}