from validator.core.constants import (
    MIN_NUMBER_OF_MINERS_FOR_KNOCKOUT_ROUND,
    PREVIOUS_WINNER_BASE_CONTESTANT,
    EXPECTED_GROUP_SIZE,
    TEXT_TASKS_PER_GROUP,
    IMAGE_TASKS_PER_GROUP
)

# Test-specific constants to avoid hardcoded strings
TEST_TOURNAMENT_PREFIX = "TEST_TOURN_"
TEST_ROUND_PREFIX = "TEST_ROUND_"
TEST_GROUP_PREFIX = "TEST_GROUP_"
TEST_PAIR_PREFIX = "TEST_PAIR_"
TEST_HOTKEY_PREFIX = "test_hotkey_"

# Test participant counts
SMALL_KNOCKOUT_COUNT = 8
LARGE_GROUP_COUNT = 20
BOUNDARY_KNOCKOUT_COUNT = MIN_NUMBER_OF_MINERS_FOR_KNOCKOUT_ROUND
BOUNDARY_GROUP_COUNT = MIN_NUMBER_OF_MINERS_FOR_KNOCKOUT_ROUND + 1
ODD_PARTICIPANT_COUNT = 7